@startuml
actor "System Administrator" as Admin
actor "Visitor" as Visitor
actor "Security Personnel" as Security
actor "Librarian" as Librarian
actor "Teacher" as Teacher
actor "Student" as Student

rectangle "Common Use Cases" {
    (Profile Management) as Profile
    (Electric Vehicle ) as EV
}

rectangle "Security Functions" {
    Security -up-> (Patrol Records)
    Security -up-> (Emergency Contact Access)
    Security -left-> EV
    Security -up-> (Violation Handling)
    Security -down-> Profile
}

rectangle "Admin Functions" {
    Admin -up-> (User Management)
    Admin -up-> (Permission Management)
    Admin -up-> (System Configuration)
    Admin -up-> (Data Backup and Recovery)
    Admin -up-> (Electric Vehicle Management System Configuration)
    Admin -down-> Profile
}

rectangle "Librarian Functions" {
    Librarian -- (Resource Management)
    Librarian -- (Borrowing Management)
    Librarian -- (Inventory Inquiry)
    Librarian -- (User Borrowing Records)
    Librarian -up-> Profile
}

rectangle "Teacher Functions" {
    Teacher -- (Course Management)
    Teacher -- (Student Management)
    Teacher -- (Assignment Management)
    Teacher -- (Resource Access)
    Teacher -- (Grade Entry)
    Teacher -up-> Profile
    Teacher -- (Discussion Forum Management)
}

rectangle "Student Functions" {
    Student -- (Course Management)
    Student -up- (Grade Inquiry)
    Student -- (Resource Access)
    Student -up-> Profile
    Student -left-> EV
}

rectangle "Visitor Functions" {
    Visitor -down-> (Information Access)
    Visitor -down-> (Resource Browsing)
    Visitor -down-> (Registration Information)
    Visitor -down-> (Contact Us)
}
@enduml
