@startuml
actor "Librarian" as Librarian

rectangle "System" {
    Librarian -- (Resource Management)
    Librarian -- (Borrowing Management)
    Librarian -- (Inventory Inquiry)
    Librarian -- (User Borrowing Records)
    Librarian -- (Announcement Posting)
    Librarian -- (Profile Management)
}
@enduml
